vim.g.mapleader = ","
vim.g.maplocalleader = " "

local opt = vim.opt

opt.completeopt = "menu,menuone,noselect"
opt.conceallevel = 3 -- hide * markup for bold and italic
opt.confirm = true -- confirm to save changes before exiting modified buffer
opt.expandtab = true -- use spaces instead of tabs
opt.formatoptions = "jcroqlnt" -- tcqj
opt.grepformat = "%f:%l:%c:%m"
opt.grepprg = "rg --vimgrep"
opt.hlsearch = false -- remove highlight after search
opt.ignorecase = true -- ignore case
opt.inccommand = "nosplit" -- preview incremental substitute
opt.laststatus = 3 -- global status line
opt.list = true -- show some invisible characters (tabs...
opt.listchars:append("tab:»·,trail:·,nbsp:␣,precedes:‹,extends:›") -- strings to use as virtual text with a lot of information opt.mouse = "a" -- enable mouse mode
opt.number = true -- print line number
opt.pumblend = 10 -- popup blend
opt.pumheight = 10 -- maximum number of entries in a popup
opt.relativenumber = true -- relative line numbers
opt.scrolloff = 4 -- lines of context
opt.sessionoptions = { "buffers", "curdir", "tabpages", "winsize" }
opt.shiftround = true -- round indent
opt.shiftwidth = 2 -- size of an indent
opt.shortmess:append({ w = true, i = true, c = true })
opt.showbreak = "↪ " -- hint shown when a line is wrapped
opt.showmode = false -- dont show mode since we have a statusline
opt.sidescrolloff = 8 -- columns of context
opt.signcolumn = "yes" -- always show the signcolumn, otherwise it would shift the text each time
opt.smartcase = true -- don't ignore case with capitals
opt.smartindent = true -- insert indents automatically
opt.spelllang = { "en" }
opt.splitbelow = true -- put new windows below current
opt.splitkeep = "screen"
opt.splitright = true -- put new windows right of current
opt.tabstop = 2 -- number of spaces tabs count for
opt.termguicolors = true -- true color support
opt.timeoutlen = 500 -- milliseconds to wait for a mapped sequence to complete
opt.undofile = true -- enable undo files to use UndoTree
opt.undolevels = 10000
opt.updatetime = 200 -- save swap file and trigger cursorhold
opt.wildmode = "longest:full,full" -- command-line completion mode
opt.wrap = false -- disable line wrap
