abbr -a e 'nvim'
abbr -a c 'clear'

abbr -a l 'ls'
abbr -a ll 'ls -l'
abbr -a lll 'ls -la'

# The following git abbreviations were taken from @fasterthanlime
# Ref: https://github.com/fasterthanlime/dotfiles/blob/main/.zshrc.d/git-alias.zsh
# Branch (b)
abbr -a gb 'git branch'
abbr -a gba 'git branch --all --verbose'
abbr -a gbc 'git checkout -b'
abbr -a gbd 'git branch --delete'
abbr -a gbD 'git branch --delete --force'
abbr -a gbl 'git branch --verbose'
abbr -a gbL 'git branch --all --verbose'
abbr -a gbm 'git branch --move'
abbr -a gbM 'git branch --move --force'
abbr -a gbr 'git branch --move'
abbr -a gbR 'git branch --move --force'
abbr -a gbs 'git show-branch'
abbr -a gbS 'git show-branch --all'
abbr -a gbv 'git branch --verbose'
abbr -a gbV 'git branch --verbose --verbose'
abbr -a gbx 'git branch --delete'
abbr -a gbX 'git branch --delete --force'
# Commit (c)
abbr -a gc 'git commit --verbose'
abbr -a gcs 'git commit --verbose --signoff'
abbr -a gca 'git commit --verbose --all'
abbr -a gcm 'git commit --message'
abbr -a gcmS 'git commit --message --gpg-sign'
abbr -a gcam 'git commit --all --message'
abbr -a gco 'git checkout'
abbr -a gcO 'git checkout --patch'
abbr -a gcf 'git commit --amend --no-edit'
abbr -a gcF 'git commit --verbose --amend'
abbr -a gcp 'git cherry-pick --ff'
abbr -a gcP 'git cherry-pick --no-commit'
abbr -a gcr 'git revert'
abbr -a gcR 'git reset "HEAD^"'
abbr -a gcs 'git show'
abbr -a gcsS 'git show --pretty=short --show-signature'
abbr -a gcl 'git-commit-lost'
abbr -a gcy 'git cherry --verbose --abbrev'
abbr -a gcY 'git cherry --verbose'
# Fetch (f)
abbr -a gf 'git fetch'
abbr -a gfa 'git fetch --all --prune'
abbr -a gfc 'git clone'
abbr -a gfcr 'git clone --recurse-submodules'
abbr -a gfm 'git pull'
abbr -a gfma 'git pull --autostash'
abbr -a gfr 'git pull --rebase'
abbr -a gfra 'git pull --rebase --autostash'
# Grep (g)
abbr -a gg 'git grep'
abbr -a ggi 'git grep --ignore-case'
abbr -a ggl 'git grep --files-with-matches'
abbr -a ggL 'git grep --files-without-matches'
abbr -a ggv 'git grep --invert-match'
abbr -a ggw 'git grep --word-regexp'
# Index (i)
abbr -a gia 'git add'
abbr -a giA 'git add --all'
abbr -a gip 'git add --patch'
abbr -a giu 'git add --update'
abbr -a gid 'git diff --no-ext-diff --cached'
abbr -a giD 'git diff --no-ext-diff --cached --word-diff'
abbr -a gii 'git update-index --assume-unchanged'
abbr -a giI 'git update-index --no-assume-unchanged'
abbr -a gir 'git reset'
abbr -a giR 'git reset --patch'
abbr -a gix 'git rm -r --cached'
abbr -a giX 'git rm -r --force --cached'
# Log (l)
abbr -a gl 'git log --topo-order'
abbr -a gls 'git log --topo-order --stat'
abbr -a gld 'git log --topo-order --stat --patch --full-diff'
abbr -a glg 'git log --topo-order --graph --abbrev-commit --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Creset(%cr) %C(bold blue)<%an>%Creset"'
abbr -a glc 'git shortlog --summary --numbered'
abbr -a glS 'git log --show-signature'
# Merge (m)
abbr -a gm 'git merge'
abbr -a gmC 'git merge --no-commit'
abbr -a gmF 'git merge --no-ff'
abbr -a gma 'git merge --abort'
abbr -a gmt 'git mergetool'
# Push (p)
abbr -a gp 'git push'
abbr -a gpf 'git push --force-with-lease'
abbr -a gpF 'git push --force'
abbr -a gpa 'git push --all'
abbr -a gpA 'git push --all && git push --tags'
abbr -a gpt 'git push --tags'
abbr -a gpc 'git push --set-upstream origin "(git-branch-current 2> /dev/null)"'
abbr -a gpp 'git pull origin "(git-branch-current 2> /dev/null)" && git push origin "(git-branch-current 2> /dev/null)"'
# Rebase (r)
abbr -a gr 'git rebase'
abbr -a gra 'git rebase --abort'
abbr -a grc 'git rebase --continue'
abbr -a gri 'git rebase --interactive'
abbr -a grs 'git rebase --skip'
# Remote (R)
abbr -a gR 'git remote'
abbr -a gRl 'git remote --verbose'
abbr -a gRa 'git remote add'
abbr -a gRx 'git remote rm'
abbr -a gRm 'git remote rename'
abbr -a gRu 'git remote update'
abbr -a gRp 'git remote prune'
abbr -a gRs 'git remote show'
abbr -a gRb 'git-hub-browse'
# Status (s)
abbr -a gs 'git status'
abbr -a gss 'git status --short'
# Stash (S)
abbr -a gS 'git stash'
abbr -a gSa 'git stash apply'
abbr -a gSx 'git stash drop'
abbr -a gSX 'git-stash-clear-interactive'
abbr -a gSl 'git stash list'
abbr -a gSd 'git stash show --patch --stat'
abbr -a gSp 'git stash pop'
abbr -a gSs 'git stash save --include-untracked'
abbr -a gSS 'git stash save --patch --no-keep-index'
abbr -a gSw 'git stash save --include-untracked --keep-index'
# Tag (t)
abbr -a gt 'git tag'
abbr -a gtl 'git tag --list'
abbr -a gts 'git tag --sign'
abbr -a gtv 'git verify-tag'
# Diff (d)
abbr -a gd 'git diff --no-ext-diff'
abbr -a gD 'git diff --no-ext-diff --word-diff'
# Reset (R)
abbr -a gr 'git reset --soft'
abbr -a gR 'git reset --hard'
# Clean (C)
abbr -a gC 'git clean --dry-run'
abbr -a gCf 'git clean --force'
# Remove (x)
abbr -a gx 'git rm -r'
abbr -a gX 'git rm -r --force'
# Worktree (w)
abbr -a gw 'git worktree'
abbr -a gwc 'git-worktree-clone'
abbr -a gwL 'git worktree lock'
abbr -a gwR 'git worktree repair'
abbr -a gwa 'git worktree add'
abbr -a gwab 'git worktree add -b'
abbr -a gwl 'git worktree list'
abbr -a gwm 'git worktree move'
abbr -a gwp 'git worktree prune'
abbr -a gwr 'git worktree remove'
abbr -a gwu 'git worktree unlock'
